name: Build and Release VS Code Extension

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')))
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm install
    
    - name: Install all dependencies
      run: npm run install-all
    
    - name: Build extension
      run: npm run compile
    
    - name: Package extension
      run: npx @vscode/vsce package --no-dependencies
    
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: jason-markdown-vsix
        path: '*.vsix'
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download VSIX artifact
      uses: actions/download-artifact@v4
      with:
        name: jason-markdown-vsix
        path: ./
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Jason's Markdown Extension v${{ steps.get_version.outputs.VERSION }}
          
          ### Changes
          - Auto-generated release from tag ${{ github.ref_name }}
          
          ### Installation
          Download the `.vsix` file and install it in VS Code using:
          ```bash
          code --install-extension jason-markdown-*.vsix
          ```
          
          Or install through VS Code Extensions view: Extensions → ... → Install from VSIX
          
        files: |
          *.vsix
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 